name: Docker Image CI for GHCR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: www-art

jobs:

  build_and_publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
    - uses: actions/checkout@v4

    - name: Update Git submodules - ie. themes
      run: git submodule update --init --recursive

    - name: Build the push the image to GitHub Container Registry (GHCR)
      run: |
        echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker build . --file Dockerfile --tag ghcr.io/jasondchambers/$IMAGE_NAME:${{ github.run_number }}
        docker push ghcr.io/jasondchambers/$IMAGE_NAME:${{ github.run_number }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/www-art:${{ github.run_number }}
